<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<RootNamespace>DivinityModManager</RootNamespace>
		<PlatformTarget>x64</PlatformTarget>
		<Platforms>x64</Platforms>
		<Configurations>Debug;Release;Publish;PublishTest</Configurations>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<SupportedCultures>en-US</SupportedCultures>
		<DebugType>none</DebugType>
		<Optimize>True</Optimize>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)'=='Debug'">
		<DebugType>full</DebugType>
		<Optimize>False</Optimize>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="$(SolutionDir)External\lslib\LSLibNative\LSLibNative.vcxproj" />
		<ProjectReference Include="$(SolutionDir)External\lslib\LSLib\LSLib.csproj" />
		<ProjectReference Include="$(SolutionDir)External\CrossSpeak\CrossSpeak\CrossSpeak.csproj" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Gameloop.Vdf" Version="0.6.2" />
		<PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="NexusModsNET" Version="1.0.5" />
		<PackageReference Include="ReactiveHistory" Version="0.10.7" />
		<PackageReference Include="ReactiveProperty" Version="9.7.0" />
		<PackageReference Include="ReactiveUI" Version="19.4.1" />
		<PackageReference Include="ReactiveUI.Fody" Version="19.4.1" />
		<PackageReference Include="System.Reactive" Version="6.0.1" />
		<PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
		<PackageReference Include="System.Net.Http" Version="4.3.4" />
	</ItemGroup>
</Project>